export const STUDENT_LOADING = 'STUDENT_LOADING'
export const STUDENT_ERROR = 'STUDENT_ERROR'
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS'

export const STUDENT_ADD_TIME_LOADING = 'STUDENT_ADD_TIME_LOADING'
export const STUDENT_ADD_TIME_ERROR = 'STUDENT_ADD_TIME_ERROR'
export const STUDENT_ADD_TIME_SUCCESS = 'STUDENT_ADD_TIME_SUCCESS'

export const ADMIN_LOADING = 'ADMIN_LOADING'
export const ADMIN_ERROR = 'ADMIN_ERROR'
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS'
